"""Initial schema

Revision ID: 0a20158039f4
Revises: 
Create Date: 2025-09-06 08:09:57.853891+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a20158039f4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_documents_api_key_name'))
        batch_op.drop_index(batch_op.f('idx_documents_created_by'))
        batch_op.drop_index(batch_op.f('idx_documents_updated_by'))
        batch_op.create_index(batch_op.f('ix_documents_api_key_name'), ['api_key_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_updated_by'), ['updated_by'], unique=False)

    with op.batch_alter_table('webpages', schema=None) as batch_op:
        batch_op.alter_column('is_seed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('idx_webpages_api_key_name'))
        batch_op.drop_index(batch_op.f('idx_webpages_created_by'))
        batch_op.drop_index(batch_op.f('idx_webpages_updated_by'))
        batch_op.create_index(batch_op.f('ix_webpages_api_key_name'), ['api_key_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_webpages_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_webpages_updated_by'), ['updated_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webpages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webpages_updated_by'))
        batch_op.drop_index(batch_op.f('ix_webpages_created_by'))
        batch_op.drop_index(batch_op.f('ix_webpages_api_key_name'))
        batch_op.create_index(batch_op.f('idx_webpages_updated_by'), ['updated_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_webpages_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_webpages_api_key_name'), ['api_key_name'], unique=False)
        batch_op.alter_column('is_seed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_updated_by'))
        batch_op.drop_index(batch_op.f('ix_documents_created_by'))
        batch_op.drop_index(batch_op.f('ix_documents_api_key_name'))
        batch_op.create_index(batch_op.f('idx_documents_updated_by'), ['updated_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_documents_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_documents_api_key_name'), ['api_key_name'], unique=False)

    # ### end Alembic commands ###
