"""Add transcriptions table

Revision ID: 2f0f322e6a1a
Revises: 8c96491a4f7c
Create Date: 2025-09-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0f322e6a1a'
down_revision = '8c96491a4f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transcriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'queued'")),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('source_object', sa.String(length=512), nullable=True),
        sa.Column('file_name', sa.String(length=255), nullable=True),
        sa.Column('content_type', sa.String(length=100), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('language', sa.String(length=64), nullable=True),
        sa.Column('language_confidence', sa.Float(), nullable=True),
        sa.Column('model_name', sa.String(length=100), nullable=False, server_default=sa.text("'whisper-large-v3-turbo'")),
        sa.Column('transcription_text', sa.Text(), nullable=True),
        sa.Column('segments', sa.JSON(), nullable=True),
        sa.Column('usage', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('requested_by', sa.String(length=100), nullable=True),
        sa.Column('api_key_name', sa.String(length=100), nullable=True),
        sa.Column('meta_data', sa.JSON(), nullable=True),
        sa.Column('prompt', sa.Text(), nullable=True),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('response_format', sa.String(length=32), nullable=True),
        sa.Column('timestamp_granularities', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            server_onupdate=sa.func.now(),
        ),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_transcriptions_api_key_name'), 'transcriptions', ['api_key_name'], unique=False)
    op.create_index(op.f('ix_transcriptions_request_id'), 'transcriptions', ['request_id'], unique=True)
    op.create_index(op.f('ix_transcriptions_requested_by'), 'transcriptions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_transcriptions_status'), 'transcriptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_status'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_requested_by'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_request_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_api_key_name'), table_name='transcriptions')
    op.drop_table('transcriptions')
    # ### end Alembic commands ###
