"""Create collections table (actual)

Revision ID: 8c96491a4f7c
Revises: dc617fa8ae20
Create Date: 2025-09-06 08:16:15.601113+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c96491a4f7c'
down_revision = 'dc617fa8ae20'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_type', sa.String(length=32), nullable=False),
    sa.Column('api_key_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('idx_collections_owner_name', ['api_key_name', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_api_key_name'), ['api_key_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_name'))
        batch_op.drop_index(batch_op.f('ix_collections_id'))
        batch_op.drop_index(batch_op.f('ix_collections_api_key_name'))
        batch_op.drop_index('idx_collections_owner_name')

    op.drop_table('collections')
    # ### end Alembic commands ###
