"""Add collections table

Revision ID: dc617fa8ae20
Revises: 0a20158039f4
Create Date: 2025-09-06 08:13:14.194573+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc617fa8ae20'
down_revision = '0a20158039f4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
